Repository WishPool-dev/WishPool-FE, pull requests merged in 2025-06, with the labels that each got.

#12 [STYLE] 폰트 설정
  public/fonts/suite/SUITE-Bold.woff2
  public/fonts/suite/SUITE-ExtraBold.woff2
  public/fonts/suite/SUITE-Heavy.woff2
  public/fonts/suite/SUITE-Light.woff2
  public/fonts/suite/SUITE-Medium.woff2
  public/fonts/suite/SUITE-Regular.woff2
  public/fonts/suite/SUITE-SemiBold.woff2
  public/fonts/suite/SUITE.css
  src/app/globals.css
  src/app/layout.tsx
  src/styles/.gitkeep
  src/styles/colors.css
  src/styles/font.ts
  src/styles/globals.css
  src/styles/theme.css
Labels: 🎨 Style, ⚙️ Setting, 🍓 새봄

#17 [FEAT] 컴포넌트: Header
  .gitignore
  package.json
  pnpm-lock.yaml
  public/images/.gitkeep
  public/images/logo.svg
  src/app/intro/page.tsx
  src/app/layout.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/products/page.tsx
  src/assets/icons/.gitkeep
  src/assets/icons/iconMap.ts
  src/assets/icons/svg/icon_back.svg
  src/assets/icons/svg/icon_cancel.svg
  src/assets/icons/svg/icon_home.svg
  src/assets/icons/svg/icon_menu.svg
  src/assets/icons/svg/icon_wish.svg
  src/components/common/Icon.tsx
  src/components/common/Icon/iconMap.ts
  src/components/layout/Header.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/IconSection.tsx
  src/components/layout/Header/NavSection.tsx
  src/styles/globals.css
  src/styles/theme.css
Labels: ✨ Feature, 🍓 새봄

#24 Feature/21 wishpool itemcard
  src/app/wishpool-detail/page.tsx
  src/app/wishpool-detail/wishpool-list/_components/ItemCard.tsx
  src/app/wishpool-detail/wishpool-list/page.tsx
Labels: ✨ Feature, 🍑 해연
