Repository WishPool-dev/WishPool-FE, pull requests merged in 2025-09, with the labels that each got.

#88 [FIX] QA 반영
  src/app/funding/intro/layout.tsx
  src/app/funding/invite/layout.tsx
  src/app/intro/layout.tsx
  src/app/intro/page.tsx
  src/app/wishpool/(builder)/intro/layout.tsx
  src/assets/icons/svg/icon_gift.svg
  src/assets/icons/svg/icon_next.svg
  src/components/common/InfoBox/InfoNotice.tsx
  src/components/common/Modal/EditModal.tsx
  src/components/home/ActiveEventSection.tsx
  src/components/layout/Header/HomeHeader.tsx
  src/components/layout/NavMenu.tsx
  src/components/mypage/MyPageItem.tsx
Labels: ✨ Feature, 🍓 새봄

#84 [FEAT] 페이지: 생일자 최종 선택 결과 공유
  src/app/wishpool/(viewer)/final/layout.tsx
  src/app/wishpool/(viewer)/final/page.tsx
  src/assets/icons/svg/icon_kakao.svg
  src/components/common/Button/Button.style.ts
  src/styles/colors.css
Labels: ✨ Feature, 🍑 해연

#93 [REFACTOR] next/Image 사용
  public/images/card.svg
  public/images/funding-pool.svg
  public/images/gift-card.svg
  public/images/gift-circle.svg
  public/images/gift.svg
  public/images/join-complete.svg
  public/images/logo.svg
  public/images/wishpool-card.svg
  src/app/funding/intro/page.tsx
  src/app/funding/invite/page.tsx
  src/app/funding/select/page.tsx
  src/app/intro/page.tsx
  src/app/mypage/page.tsx
  src/app/wishpool/(builder)/preview/page.tsx
  src/app/wishpool/(viewer)/[id]/(detail)/page.tsx
  src/app/wishpool/join/([id])/complete/page.tsx
  src/app/wishpool/join/([id])/info/page.tsx
  src/app/wishpool/join/([id])/intro/page.tsx
  src/app/wishpool/join/([id])/preview/page.tsx
  src/assets/images/congrats.png
  src/assets/images/feedback-gift.png
  src/assets/images/gift-card.png
  src/assets/images/onboarding-1.jpg
  src/assets/images/pick-pool.png
  src/assets/images/wishpool-card.png
  src/assets/images/wishpool-gift.png
  src/components/common/EventCard.tsx
  src/components/common/FeedbackBox.tsx
  src/components/funding/list/GiftCard.tsx
  src/components/funding/select/CarouselCard.tsx
  src/components/home/CreateEventSection.tsx
  src/components/layout/Header/HomeHeader.tsx
  src/components/wishpool/viewer/list/ItemCard.tsx
Labels: 🛠️ Refactor, 🍓 새봄

#101 [Feat] 피드백 api 연결
  src/api/domain/feedback/hook.ts
  src/api/domain/feedback/index.ts
  src/api/domain/feedback/types.ts
  src/app/feedback/page.tsx
  src/components/common/Form/TextField.tsx
  src/components/common/Rating.tsx
  src/constants/common/endPoint.ts
  src/types/wishpool/builder/Form.ts
Labels: 📬 API, 🍓 새봄
