Repository WishPool-dev/WishPool-FE, pull requests merged in 2025-05, with the labels that each got.

#2 [Init] 개발 환경 세팅
  .prettierrc
  eslint.config.mjs
  next.config.ts
  package.json
  pnpm-lock.yaml
  public/images/.gitkeep
  src/app/layout.tsx
  src/assets/icons/.gitkeep
  src/assets/images/.gitkeep
  src/components/ReactQueryProvider.tsx
  src/components/common/Button.tsx
  src/components/common/Icon/Icon.tsx
  src/components/common/Icon/iconMap.ts
  src/components/common/index.ts
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/index.ts
  src/components/ui/Modal.tsx
  src/components/ui/index.ts
  src/constants/.gitkeep
  src/lib/queryClient.ts
  src/queries/.gitkeep
  src/store/.gitkeep
  src/styles/.gitkeep
  src/types/svg.d.ts
  src/utils/.gitkeep
Labels: ⚙️ Setting, ✨ Feature

#4 [INIT] 허스키 설정
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.ts
  package.json
  pnpm-lock.yaml
Labels: ⚙️ Setting

#6 [CHORE] 순서 정렬
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/ReactQueryProvider.tsx
  tsconfig.json
Labels: ⚙️ Setting, 🍓 새봄

#8 [CHORE] CI 환경 구축
  .github/workflows/ci.yml
Labels: ⚙️ Setting, 🍓 새봄

#11 [STYLE] 컬러 시스템 추가
  src/app/colors.css
  src/app/globals.css
Labels: 🎨 Style, 🍑 해연
